### ISSUE TITLE
Create icon slot and pass it to AssetId component instead of hardcoding.

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/apps#110]
I'm thinking maybe better approach would be to build warning/danger icon here and pass it as slotted to AssetId component. That way we don't have to change API of assetId with every change and we can keep it clean for extension by slotting. So maybe to create named slot badge instead ?

_Originally posted by @nohaapav in https://github.com/galacticcouncil/apps/pull/109#discussion_r1570438918_

**Comment by nohaapav** [comment]
Done

**Comment by jak-pan** [comment]
💨
