### ISSUE TITLE
Swap GLMR x-chain fees from payment currency

### ISSUE THREAD

**Issue by mrq1911** [galacticcouncil/apps#119]
Currently wormhole transfers from HydraDX through Moonbeam, we require users to have some 0.1 GLMR in their HydraDX wallet only so we can transfer it to Moonbeam and pay for transact 0.07 GLMR (0.03 is margin) with it.

We should add a swap of this 0.1 GLMR from wallet payment currency into the batch so the user doesn't have to do it manually and that we don't spend their GLMR from the wallet unexpectedly.

Bonus: we can check the balance of their MDA and if it is already more than 0.1 GLMR we don't have to perform transfer at all as they have gathered enough GLMR from fee margins.

**Comment by nohaapav** [comment]
Done
