### ISSUE TITLE
Decimal places

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/apps#13]
Number of d.p. seem somewhat excessive :D 

<img width="815" alt="image" src="https://user-images.githubusercontent.com/97540577/205968459-f375d231-407e-48fa-a07d-62a3c8da2f8d.png">

**Comment by lolmcshizz** [comment]
![Image](https://user-images.githubusercontent.com/97540577/206515647-6cfbcc9c-4d66-4d53-818c-e6c331b57641.png)

Can we also fix no of d.p. on recent activities/ notifications please?

**Comment by nohaapav** [comment]
should be fixed in notif / activities
