### ISSUE TITLE
trading 0000 for 0

### ISSUE THREAD

**Issue by lumir-mrkva** [galacticcouncil/apps#16]
<img width="524" alt="Screenshot 2022-12-06 at 20 14 20" src="https://user-images.githubusercontent.com/2580779/206001543-0f5483b7-3691-45de-84f4-50db046e4c2e.png">

**Comment by nohaapav** [comment]
@lumir-mrkva We can maybe use this mask:
https://imask.js.org/guide.html#masked-number
