### ISSUE TITLE
You can scroll numbers up or down in YOU GET/ PAY WITH

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/apps#24]
Unsure if feature or a bug, but this user feels that this could cause errors for people unintentionally scrolling the value up or down

https://user-images.githubusercontent.com/97540577/206429529-5d6fc628-bb30-43a8-824c-8993bf87493f.mp4

**Comment by nohaapav** [comment]
Basically its intended behaviour of html input if type number specified .. however not really welcome here.
