### ISSUE TITLE
Price of numbers doesn't change when switching asset location

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/apps#25]
the price of 1 HDX in DOT remains regardless of whether you are "PAY WITH" DOT or HDX

<img width="558" alt="image" src="https://user-images.githubusercontent.com/97540577/206429934-68936759-fa4b-4abb-9ae1-e6f7192caf19.png">

**Comment by nohaapav** [comment]
We discussed this one yesterday
