### ISSUE TITLE
Inconsistencies in PAY WITH/ YOU GET/ Buy/ Sell

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/apps#26]
**Issue related to "recent activities" / notification flow implementation**

**Example:** I enter 1 DAI into the "YOU GET" field (so I am buying DAI for HDX, or selling HDX for DAI), when my transaction is submitted, processing and completed it is labelled in the notification flow as "Buy xxxx HDX for 1 DAI submitted" - which is incorrect.

![](https://user-images.githubusercontent.com/97540577/206179134-85edcb55-4079-4d4e-8644-473e1462c51c.png)

**Comment by nohaapav** [comment]
1. You fill PAY WITH -> You're selling HDX and getting DAI
2. You fill YOU GET -> You're buying DAI for HDX 

On transaction layer naming is correct, from user perspective, you're right.
