### ISSUE TITLE
Number Spacing

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/apps#4]
Numbers should be spaced according to current trade page implementation, i.e. 10000 (typed) should be formatted as 10 000. I have also included a screenshot of current implementation.

**Edit:** The number spacing issue also appears with the balances displayed just above the input field.

<img width="740" alt="Screenshot 2022-11-04 at 11 47 00" src="https://user-images.githubusercontent.com/97540577/199965408-1adeb08c-13ac-40ac-a507-fb667fd4d591.png">

<img width="740" alt="Screenshot 2022-11-04 at 11 48 41" src="https://user-images.githubusercontent.com/97540577/199965661-32ec1866-383b-4f36-ac2f-db95f7d9d55f.png">

**Comment by lolmcshizz** [comment]
USD pricing beneath the input should also be formatted in the same way :)

![Image](https://user-images.githubusercontent.com/97540577/207567935-52b8483f-c674-4474-802b-6ada31964e82.png)

**Comment by nohaapav** [comment]
@lolmcshizz ok mama :) I knew you're going to notice ..

**Comment by lolmcshizz** [comment]
https://tenor.com/biLQ9.gif
