### ISSUE TITLE
MAX BUTTON - failed tx when using BSX (fee payment asset)

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/apps#46]
Tested max button with selling aUSD, worked fine - when trying to use it with BSX (which is my fee payment asset) it is failing.

I switched my fee payment asset to KSM, and the BSX MAX button worked fine again. Tried to max sell KSM and it failed. So the issue appears to be related to the fee payment.

![image](https://user-images.githubusercontent.com/97540577/216587486-cb2358e8-7572-4225-873d-d28fa1b697bd.png)

**Comment by nohaapav** [comment]
I believe this is fixed already. Closing.
