### ISSUE TITLE
Minimal trade limit warning

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/apps#48]
The warning for minimal trade limit should probably be raised, as currently it only kicks in for trades of e.g. 0.000000001 are still valid (despite being worth 0)

![image](https://user-images.githubusercontent.com/97540577/216590665-91d0a994-668a-4708-8a50-66ff7b0dea49.png)

**Comment by nohaapav** [comment]
@lolmcshizz Trading limit is configured in runtime. Not in UI. We have to ask runtime team to change the limit.
