### ISSUE TITLE
Should we clear fields after submitting tx?

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/apps#6]
Maybe not a bug but perhaps needs a decision - should we clear the fields once we've submitted a tx?

Initially I was a little lost once the tx pending toast disappeared, but I note your comment that the full notification flow inc. pending tx bells etc will come at a later time - I like that we're not blocking further action once tx is submitted, but perhaps it would be more user friendly to clear all fields once the tx is submitted? I believe we've had this as feedback from the community previously.

https://user-images.githubusercontent.com/97540577/199968528-c76639ea-4a0c-4f72-afa4-f7dc51271bb8.mov

**Comment by nohaapav** [comment]
I believe it will be clear once we show this dialog on confirmation:
<img width="322" alt="Screen Shot 2022-11-04 at 10 25 53 AM" src="https://user-images.githubusercontent.com/4179104/200068204-e0d7c564-9bb9-45d8-83bc-90980d12f418.png">

Should be easy to implement in first phase and then we don't have to show broadcasting toast & only transaction successful / error toast will be displayed once in block. In current trade app we have toast that is rewriting state and staying on screen until TX in block but that is terrible toast anti pattern .. 

Maybe, and i want to discuss this further it would be nice to have floating icon with badge in bottom right corner so you can click to see progress - icon can have progress if there is some TX running, and then on click you are going to see drawer with TX progress .. 

Like this:

![Uploading Screen Shot 2022-11-04 at 10.34.56 AM.png…]()

I'll try to prepare small demonstration, you are going to like it, i'm telling you @lolmcshizz

**Comment by lolmcshizz** [comment]
![Screenshot_20221105_083850](https://user-images.githubusercontent.com/97540577/200111301-60984ac9-c916-4a2c-81a6-1c580afa978a.jpg)

Img won't load ;_;

**Comment by nohaapav** [comment]
Check now, if clearance is still required i can reset the form on submit. Anyway i don't really like the idea of reset as if i wanna do partial swaps my input is wiped after each confirmation ..

**Comment by nohaapav** [comment]
Closing, feel free to reopen if still relevant. I guess users are ok with current behavior.
