### ISSUE TITLE
Swaps with old information in the UI- when new calcs is not finished

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/apps#61]
allows swap with old info if you are very fast and the UI has not updated, despite writing new info in the UI

![IMG_20230201_133735_828](https://user-images.githubusercontent.com/123791232/216120554-5c1411b9-bd54-4307-a45b-b3fd96968693.jpg)

Some feedback
![IMG_20230201_134944](https://user-images.githubusercontent.com/123791232/216123026-f7b43b89-c452-449c-9bcf-af8a22f44d03.jpg)

**Comment by nohaapav** [comment]
i think this shouldn't be a problem with SDK caching atm .. unless user is faster than 150ms .. (Clark Kent)
