### ISSUE TITLE
DCA & Split Trade Improvements

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/apps#76]
### DCA Page

Implement updated design (below) - more user (and whale) friendly UI, uses similar Split Trade logic to remove the need for the user to determine their own frequency of trades. Also adds additional customisable options for power users.

![telegram-cloud-photo-size-4-5769557387399773457-y](https://github.com/galacticcouncil/HydraDX-ui/assets/97540577/16a4ab1f-dc34-495f-947b-9c5598447e78)

### Split Trade

- Increase max time cap from 3 hours to 6 hours so schedules are less aggressive
- Increase number of retries from 1 to 3
- In `settings` cog on trade page, add additional slippage field for split trades specifically
- In `settings` cog on trade page, add max retries custom field
- Block `schedule trade` if the resultant schedule slippage is > their slippage limit (as these would only fail)
- Point user towards DCA UI if suitable schedule cannot be found in split trade function, as more customisable

### Error Messaging

If a single DCA trade fails due to slippage limit, the error message should say something to the effect of `Slippage limit reached, retrying...`. If the schedule in it's entirety fails due to repeated failures, the error message should say something to the effect of `Maximum retries exhausted, please reschedule trade with adjusted parameters`.

**Comment by DuriSK** [comment]
done
