### ISSUE TITLE
Max buttom on swap with asset fee is not working well

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/apps#77]
The max buttom when swap the asset fee to other asset is not taking in account well the fees, so the tx fail, but still charge the fees

Can be confusing 

In the video my asset fee us USDT 

https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/0560118a-d91e-4011-af3e-e21de63cc3b2

**Comment by nohaapav** [comment]
Fixed in master
