### ISSUE TITLE
Graph is not redrawn correctly in UI when I switch the buy/sell assets

### ISSUE THREAD

**Issue by poliwop** [galacticcouncil/apps#82]
I had a DOT/USDT swap set up, specifically buying DOT with USDT. The graph looked correct. Note that the highest price label is 8.9574 while the lowest price label is 7.6338. This is a reasonable range for the DOT price for the last week.
![UIBugBeforeSwitch](https://github.com/galacticcouncil/HydraDX-ui/assets/5674266/4306de0b-0486-43af-8f41-1abcf88eb369)

Then I clicked the arrow between the USDT and DOT amount windows, to switch DOT to the "pay" asset (i.e. sell asset) and USDT to the "buy" asset. The graph was redrawn, but the highest price label *remained at 8.9574*, while the lowest price label dropped to 0.1285. 0.1285 is reasonable for the USDT/DOT price, but the USDT/DOT price has not been anywhere close to 9 anytime recently.

It's harder for me to tell if the graph itself is right, but it looks wrong to me... it doesn't have the same volatility as the DOT/USDT graph, and they should have similar price volatility.

![UIBugAfterSwitch](https://github.com/galacticcouncil/HydraDX-ui/assets/5674266/b1ab61fc-96cd-4c41-836a-8c90729ca89a)

I don't think this matters but I'm using Brave browser on Ubuntu.

**Comment by nohaapav** [comment]
Fixed in master
