### ISSUE TITLE
Add switching of price by clicking

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/apps#86]
When using the trade UI, the price is determined by which asset is in `PAY WITH` and `YOU GET` - it would be useful to be able to change it by clicking the price

![image](https://github.com/galacticcouncil/apps/assets/97540577/e9d5fbfd-3d16-4941-a6d3-976c0fb43895)

Example below from uniswap after clicking the price

<img width="505" alt="image" src="https://github.com/galacticcouncil/apps/assets/97540577/a83ba942-457d-4460-99e5-c32175c41bda">

<img width="486" alt="image" src="https://github.com/galacticcouncil/apps/assets/97540577/f73813dd-7846-4668-a4a2-67fc04b9a262">

**Comment by nohaapav** [comment]
Done in  master
