### ISSUE TITLE
Add asset switcher to DCA UI

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/apps#88]
Currently to switch the assets around in the DCA UI, you need to do a 3-step swap involving a third asset - we should add the asset switcher from trade UI to this page.

![image](https://github.com/galacticcouncil/apps/assets/97540577/cb53e426-387c-4dc3-b7fa-b883519cc57e)

![image](https://github.com/galacticcouncil/apps/assets/97540577/43b4eb86-0c28-4f2a-bd10-c72dc27cbb23)

**Comment by nohaapav** [comment]
Fixed in master
