### ISSUE TITLE
Yield dca little issue

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/apps#90]
even though the "schedule dca trades" button is greyed out due the min amount is not reached, if I click on it, it seems I can move forward
<img width="756" alt="image-33" src="https://github.com/galacticcouncil/apps/assets/123791232/0d119be1-fa64-4fb1-901f-d5cac2346900">
<img width="1507" alt="image-14" src="https://github.com/galacticcouncil/apps/assets/123791232/4d085774-e861-4ed1-829b-5fceea3b0380">

**Comment by nohaapav** [comment]
Fixed in master
